"""cria tabela activities

Revision ID: d7fadad07115
Revises: 8bd034e3e802
Create Date: 2026-09-30 21:20:33.677829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7fadad07115'
down_revision: Union[str, None] = '8bd034e3e802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('RUN', 'WALK', 'CYCLE', 'HIKE', 'SWIM', 'OTHER', name='activity_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elevation_gain_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_pace_s_per_km', sa.Integer(), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('route', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw_track_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories IS NULL OR calories >= 0', name='ck_calories_non_negative'),
    sa.CheckConstraint('distance_m IS NULL OR distance_m >= 0', name='ck_distance_non_negative'),
    sa.CheckConstraint('duration_s IS NULL OR duration_s >= 0', name='ck_duration_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_started_at'), 'activities', ['started_at'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_index('ix_activities_user_started', 'activities', ['user_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_user_started', table_name='activities')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_started_at'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
